# Language Conversation AI Configuration

# Model settings
models:
  llm: "gpt-oss:20b"
  fallback_llm: "llama3.1:8b"
  
# Ollama settings
ollama:
  host: "localhost"
  port: 11434
  timeout: 60

# Audio settings
audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024

# Application settings
app:
  debug: true
  log_level: "INFO"
  
# Future components (for later implementation)
stt:
  engine: "whisper"
  model: "base"
  
tts:
  engine: "piper"
  voice: "en_US-lessac-medium"
