# Language Conversation AI Configuration

# Model settings
models:
  llm: "gpt-oss:20b"
  fallback_llm: "llama3.1:8b"
  
# Ollama settings
ollama:
  host: "localhost"
  port: 11434
  timeout: 60

# Audio settings
audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024
  format: "wav"

# STT settings
stt:
  engine: "whisper"
  whisper_cpp_path: "whisper/whisper-cli.exe"
  model_path: null
  
# TTS settings
tts:
  engine: "piper"
  piper_path: "piper/piper.exe"
  voices_path: "piper/espeak-ng-data/voices/lv"
  default_voice: "Andrea"

# Application settings
app:
  debug: true
  log_level: "INFO"
  mode: "mixed"